# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$a^2leqa_M^2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{AMS}35Q30,41A25,41A30,65D99,65M12,65M50,65M60,76D05{AMS}/;
$cached_env_img{$key} = ' <IMG WIDTH=560 HEIGHT=12 ALIGN=BOTTOM ALT="AMS113" SRC="img3.gif"  > '; 
$key = q/{_inline}$d_12,i=fracdudy(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=95 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline1418" SRC="img25.gif"  > '; 
$key = q/{displaymath}widehata_i^2in[1,widehat{}sigma^-2]cup[widehat{}sigma^-4,infty).{displaymath}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$epsilonnm${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$H_j(x)${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$epsilon_rmM,i^(1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=26 HEIGHT=34 ALIGN=MIDDLE ALT="tex2html_wrap_inline1550" SRC="img69.gif"  > '; 
$key = q/{_inline}$C_n={i_n}${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$O(k^2)${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$ngeq1${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$sigma_M${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{displaymath}frac1j!e^-x^2H_j(x)leqe^-fracx^22kfrac2^n2sqrtn!{displaymath}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$widehata_i^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1564" SRC="img78.gif"  > '; 
$key = q/{_inline}$a_0^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1496" SRC="img52.gif"  > '; 
$key = q/{_inline}$widehatr_i${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$xi${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$a_0^4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1492" SRC="img48.gif"  > '; 
$key = q/{_inline}$k=1.086435ldots${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{align}widehatx;SPMamp;=fracx-x_i2sigma_i,nonumberwidehaty;SPMamp;=fracy-y_i2sigma_i,{align}/;
$cached_env_img{$key} = ''; 
$key = q/{displaymath}widehatr_i=sqrtwidehatx_i^2+widehaty_i^2.{displaymath}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$sim${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$s_i=1${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$etaxi=1${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$widehat{}sigma_i;SPMgt;1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=84 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline1566" SRC="img79.gif"  > '; 
$key = q/{_inline}$1a_i^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=30 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1406" SRC="img17.gif"  > '; 
$key = q/{_inline}$eta=widehat{}sigma_i^2widehata_i^-2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$gamma_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline1394" SRC="img9.gif"  > '; 
$key = q/{_inline}$fracpartial^2u_ipartialx_j^2deltax_j^2;SPMlt;;SPMlt;1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=93 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline1522" SRC="img54.gif"  > '; 
$key = q/{_inline}$d_11,i=fracdudx(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=95 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline1416" SRC="img24.gif"  > '; 
$key = q/{keywords}vortexmethods,vorticitydynamics,computationalfluiddynamics{keywords}/;
$cached_env_img{$key} = ' <IMG WIDTH=477 HEIGHT=12 ALIGN=BOTTOM ALT="keywords111" SRC="img2.gif"  > '; 
$key = q/{_inline}$s_i=sin(theta_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=76 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1398" SRC="img13.gif"  > '; 
$key = q/{_inline}$gamma_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline1468" SRC="img38.gif"  > '; 
$key = q/{_inline}$alphal${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline1424" SRC="img27.gif"  > '; 
$key = q/{_inline}$|vx_i_j-vx_i_k|;SPMlt;l${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$sigma_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline1420" SRC="img26.gif"  > '; 
$key = q/{_inline}$epsilon${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$eta${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{displaymath}frac11-widehat{}sigma_i^-2widehata_i^2+frac11-widehat{}sigma_i^2widehata_i^-2=1,{displaymath}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$sigma_m${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$Dvecu(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=48 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1414" SRC="img23.gif"  > '; 
$key = q/{_inline}$theta_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1400" SRC="img14.gif"  > '; 
$key = q/{_inline}$widehaty${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1560" SRC="img74.gif"  > '; 
$key = q/{_inline}$10^-3${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=31 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline1378" SRC="img1.gif"  > '; 
$key = q/{_inline}$sigma_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline1470" SRC="img39.gif"  > '; 
$key = q/{_inline}$a_i;SPMlt;1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=42 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline1408" SRC="img18.gif"  > '; 
$key = q/{_inline}$vecu(vx_i)=bmatrixu_iv_ibmatrix${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=84 HEIGHT=48 ALIGN=MIDDLE ALT="tex2html_wrap_inline1412" SRC="img22.gif"  > '; 
$key = q/{_inline}$vx_i=bmatrixx_iy_ibmatrix${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=62 HEIGHT=48 ALIGN=MIDDLE ALT="tex2html_wrap_inline1392" SRC="img8.gif"  > '; 
$key = q/{multline}epsilon_rmM,i(vx)=e^left[-fracfracx^2a_0^2+y^2a_0^24sigma_0^2right]-fracsigma_0^2sigma_i^2e^left[-frac(x-x_i)^2(fracc_i^2a_i^2+s_i^2a_i^2)+(y-y_i)^2(c_i^2a_i^2+fracs_i^2a_i^2)+2(x-x_i)(y-y_i)c_is_i(a_i^-2-a_i^2)4sigma_i^2right]{multline}/;
$cached_env_img{$key} = ' <IMG WIDTH=572 HEIGHT=127 ALIGN=BOTTOM ALT="multline282" SRC="img63.gif"  > '; 
$key = q/{_inline}$epsilon_rmM${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=18 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline1542" SRC="img64.gif"  > '; 
$key = q/{_inline}$theta_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1474" SRC="img40.gif"  > '; 
$key = q/{_inline}$lrightarrow0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=38 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline1458" SRC="img36.gif"  > '; 
$key = q/{_inline}$eta_M${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$alpha${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline1454" SRC="img34.gif"  > '; 
$key = q/{_inline}$arctan(widehatywidehatx)${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{figure}[t]centerepsfysize=2.5inepsfboxfigsminmax.epscenterlabelfig.minmax{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=471 HEIGHT=282 ALIGN=BOTTOM ALT="figure349" SRC="img72.gif"  > '; 
$key = q/{_inline}$sigma_i^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1402" SRC="img15.gif"  > '; 
$key = q/{_inline}$a_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline1456" SRC="img35.gif"  > '; 
$key = q/{_inline}$|vx_i-vx_j|;SPMlt;;SPMlt;l${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=102 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline1444" SRC="img33.gif"  > '; 
$key = q/{_inline}$widehatx=0${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$widehaty=0${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{figure}[t]centerparbox2.5inepsfxsize=2.5inepsfboxfigsdipole5f0020con.epsparbox2.5inepsfxsize=2.5inepsfboxfigsdipole5f0020errA.epscenterlabelfig.dipole1{figure}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$widehat{}sigma_i;SPMlt;1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=84 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline1562" SRC="img77.gif"  > '; 
$key = q/{_inline}$g_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline1390" SRC="img7.gif"  > '; 
$key = q/{multline}|epsilon_rmM,i^(1)|_infty=maxleft{|1-widehat{}sigma_i^-2|,left|(1-widehat{}sigma_i^2widehata_i^2)(widehat{}sigma_i^4widehata_i^2)^left(frac1widehat{}sigma_i^-2widehata_i^-2-1right)right|,left|(1-widehat{}sigma_i^2widehata_i^-2)(widehat{}sigma_i^4widehata_i^-2)^left(frac1widehat{}sigma_i^-2widehata_i^2-1right)right|right}.{multline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$a_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline1488" SRC="img45.gif"  > '; 
$key = q/{_inline}$theta_0=0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1520" SRC="img53.gif"  > '; 
$key = q/{gather}epsilon_rmM,i^(1)(vx)=e^left[-fracfracx^2a_0^2+y^2a_0^24sigma_0^2right]-fracsigma_0^2sigma_i^2e^left[-fracfracx^2a_i^2+y^2a_i^24sigma_i^2right]nonumberepsilon_rmM,i^(2)(vx)=fracsigma_0^2sigma_i^2left{e^left[-fracfracx^2a_i^2+y^2a_i^24sigma_i^2right]-e^left[-fracfrac(x-x_i)^2a_i^2+(y-y_i)^2a_i^24sigma_i^2right]right}nonumber{gather}/;
$cached_env_img{$key} = ' <IMG WIDTH=372 HEIGHT=159 ALIGN=BOTTOM ALT="gather300" SRC="img67.gif"  > '; 
$key = q/{figure}[t]centerparbox2.5inepsfxsize=2.5inepsfboxfigsdipole5f0020pmA.epsparbox2.5inepsfxsize=2.5inepsfboxfigsdipole5f0020pmB.epscenterlabelfig.merge-event{figure}/;
$cached_env_img{$key} = ''; 
$key = q/{tabular}|l||l|l|l|l|l|hlineStep;SPMamp;Element;SPMamp;_inline$sigma_0^2$_inline;SPMamp;_inline$a_0^2$_inline;SPMamp;rel.err.;SPMamp;abs.errhlinehline1;SPMamp;2144;SPMamp;0.0162;SPMamp;1.85;SPMamp;0.0;SPMamp;0.0hline2;SPMamp;1934;SPMamp;0.0169;SPMamp;1.90;SPMamp;0.0811;SPMamp;0.00370hline3;SPMamp;822;SPMamp;0.0180;SPMamp;1.99;SPMamp;0.159;SPMamp;0.0138hline4;SPMamp;574;SPMamp;0.0190;SPMamp;2.02;SPMamp;0.275;SPMamp;0.0360hline{tabular}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$i_m${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$vx_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1410" SRC="img20.gif"  > '; 
$key = q/{_inline}$c_i=0${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{displaymath}f(eta,xi)=(1-eta)(etaxi)^fraceta1-eta{displaymath}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$deltavx${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=17 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline1524" SRC="img55.gif"  > '; 
$key = q/{multline}epsilon_rmM,i^(3)(vx)=fracsigma_0^2sigma_i^2left{e^left[-fracfrac(x-x_i)^2a_i^2+(y-y_i)^2a_i^24sigma_i^2right]-right.nonumberleft.e^left[-frac(x-x_i)^2(fracc_i^2a_i^2+s_i^2a_i^2)+(y-y_i)^2(c_i^2a_i^2+fracs_i^2a_i^2)+2(x-x_i)(y-y_i)c_is_i(a_i^-2-a_i^2)4sigma_i^2right]right}{multline}/;
$cached_env_img{$key} = ' <IMG WIDTH=553 HEIGHT=192 ALIGN=BOTTOM ALT="multline318" SRC="img68.gif"  > '; 
$key = q/{displaymath}widehata_i^2in[1,widehat{}sigma_i^2]cup[widehat{}sigma_i^4,infty){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=363 HEIGHT=28 ALIGN=BOTTOM ALT="displaymath1502" SRC="img80.gif"  > '; 
$key = q/{displaymath}g(vecx;gamma_k_0,vx_k_0,sigma_k_0,a_k_0,theta_k_0).{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=339 HEIGHT=16 ALIGN=BOTTOM ALT="displaymath1501" SRC="img58.gif"  > '; 
$key = q/{_inline}$a_i^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1404" SRC="img16.gif"  > '; 
$key = q/{_inline}$epsilon_rmM,i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=26 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline1544" SRC="img65.gif"  > '; 
$key = q/{_inline}$alphain(0,1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=64 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1426" SRC="img28.gif"  > '; 
$key = q/{_inline}$alphalleqsigma_ileql${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=76 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1430" SRC="img30.gif"  > '; 
$key = q/{_inline}$epsilon_rmM,i^(3)${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{displaymath}frac11-widehata^2widehat{}sigma^2+frac11-widehata^-2widehat{}sigma^-2=1,{displaymath}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$vx_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1466" SRC="img37.gif"  > '; 
$key = q/{_inline}$(x_i,y_i)${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$O(N^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1438" SRC="img32.gif"  > '; 
$key = q/{align}widehatx;SPMamp;=fracx2sigma_ia_i,nonumberwidehaty;SPMamp;=fracya_i2sigma_i,{align}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$alpharightarrow1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=42 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline1428" SRC="img29.gif"  > '; 
$key = q/{_inline}$sigma^2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$nu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline1388" SRC="img5.gif"  > '; 
$key = q/{_inline}$sigma^2;SPMlt;l^2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$xi=widehat{}sigma_i^2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$widehat{}sigma_i^2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$j^textth${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{figure}[t]centerepsfysize=2.5inepsfboxfigssize.epscenter{figure}/;
$cached_env_img{$key} = ''; 
$key = q/{displaymath}sum_i=1^ng(vecx;gamma_k_i,vx_k_i,sigma_k_i,a_k_i,theta_k_i),{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=349 HEIGHT=43 ALIGN=BOTTOM ALT="displaymath1500" SRC="img57.gif"  > '; 
$key = q/{_inline}$epsilon_rmM(vecx)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=39 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1540" SRC="img61.gif"  > '; 
$key = q/{_inline}$xi_M${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$Dvu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline1530" SRC="img56.gif"  > '; 
$key = q/{_inline}$C_n${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$a^2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$m;SPMlt;N_1${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{displaymath}|H_1(x)e^-x^2|_infty=0.86ldots,{displaymath}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$f(eta,xi)=1-eta${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{align}widehatx;SPMamp;=fracx2sigma_0a_0,nonumberwidehaty;SPMamp;=fracya_02sigma_0,nonumberwidehata_i;SPMamp;=fraca_ia_0,nonumberwidehat{}sigma_i;SPMamp;=fracsigma_isigma_0.{align}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$(eta,xi)${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$C={i_1,i_2,ldots,i_N_1}${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$epsilon_rmM,i^(2)${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$c_i=cos(theta_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=79 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1396" SRC="img12.gif"  > '; 
$key = q/{_inline}$theta_k_0=0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1536" SRC="img60.gif"  > '; 
$key = q/{_inline}$eta=widehat{}sigma_i^2widehata_i^2${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$O(NlogN)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=78 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1436" SRC="img31.gif"  > '; 
$key = q/{_inline}$widehatx${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$tr_i;SPMlt;1${_inline}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$x^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline1478" SRC="img42.gif"  > '; 
$key = q/{_inline}$y^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline1482" SRC="img43.gif"  > '; 
$key = q/{_inline}$vx_k_0=v0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=53 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline1534" SRC="img59.gif"  > '; 

1;

