# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$theta_0=0,gamma_0=1,a_0;SPMgt;1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=146 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2889" SRC="img196.gif"  > '; 
$key = q/{_inline}$x^(1)=x${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=56 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2555" SRC="img110.gif"  > '; 
$key = q/{_inline}$f=nablatimesvu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=72 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2361" SRC="img29.gif"  > '; 
$key = q/{_inline}$D^2vecu(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=55 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2533" SRC="img100.gif"  > '; 
$key = q/{_inline}$l^2=3.5times10^-2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=105 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2339" SRC="img17.gif"  > '; 
$key = q/{AMS}35Q30,41A25,41A30,65D99,65M12,65M50,65M60,76D05{AMS}/;
$cached_env_img{$key} = ' <IMG WIDTH=560 HEIGHT=12 ALIGN=BOTTOM ALT="AMS74" SRC="img21.gif"  > '; 
$key = q/{_inline}$l^2=6.4times10^-3${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=105 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline3107" SRC="img255.gif"  > '; 
$key = q/{_inline}$d_11=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=50 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2919" SRC="img214.gif"  > '; 
$key = q/{figure}[t]centerepsfysize=2.5inepsfboxfigslambda.epscenterlabelfig.lambda{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=387 HEIGHT=286 ALIGN=BOTTOM ALT="figure329" SRC="img94.gif"  > '; 
$key = q/{_inline}$vecu(vx_i)=u_ibrackv_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=80 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2413" SRC="img58.gif"  > '; 
$key = q/{figure}[t]centerparbox2.5inepsfxsize=2.5inepsfboxfigsvel.epsparbox2.5inepsfxsize=2.5inepsfboxfigsveldev.epscenterlabelfig.vel{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=555 HEIGHT=226 ALIGN=BOTTOM ALT="figure884" SRC="img194.gif"  > '; 
$key = q/{_inline}$u^(2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=25 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline3127" SRC="img257.gif"  > '; 
$key = q/{_inline}$|a^-1-a|leq2R_calE=O(l^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=168 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2583" SRC="img123.gif"  > '; 
$key = q/{_inline}$vecx${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2541" SRC="img260.gif"  > '; 
$key = q/{_inline}$omega(x,y,t)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=59 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2351" SRC="img23.gif"  > '; 
$key = q/{_inline}$(barx,bary)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2635" SRC="img143.gif"  > '; 
$key = q/{_inline}$c_i=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=40 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2551" SRC="img107.gif"  > '; 
$key = q/{_inline}$xirightarrow0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=40 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2645" SRC="img150.gif"  > '; 
$key = q/{_inline}$sigma=l${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2925" SRC="img217.gif"  > '; 
$key = q/{figure}[t]centerparbox2.5inepsfxsize=2.5inepsfboxfigspsi1a.epsparbox2.5inepsfxsize=2.5inepsfboxfigspsi1b.epscenterlabelfig.psi1{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=548 HEIGHT=226 ALIGN=BOTTOM ALT="figure615" SRC="img172.gif"  > '; 
$key = q/{_inline}$alpharightarrow0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=43 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2959" SRC="img226.gif"  > '; 
$key = q/{_inline}$vx_i=vec0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2549" SRC="img106.gif"  > '; 
$key = q/{_inline}$nablacdotvecu=0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=62 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline2359" SRC="img28.gif"  > '; 
$key = q/{_inline}$groupd_12,i+d_21,igroupover2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=62 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline2301" SRC="img93.gif"  > '; 
$key = q/{_inline}$a_0rightarrow1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=47 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2961" SRC="img227.gif"  > '; 
$key = q/{_inline}$C_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline2743" SRC="img181.gif"  > '; 
$key = q/{_inline}$d_11,i=duoverdx(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=95 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2417" SRC="img60.gif"  > '; 
$key = q/{_inline}$a^2-1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=42 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2461" SRC="img76.gif"  > '; 
$key = q/{_inline}$R=oR${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=45 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2733" SRC="img175.gif"  > '; 
$key = q/{_inline}$s_i=sin(theta_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=76 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2401" SRC="img49.gif"  > '; 
$key = q/{_inline}$widehatomega(vecx)-omega(vecx)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=82 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3071" SRC="img12.gif"  > '; 
$key = q/{_inline}$d_12=d_21=0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=94 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2921" SRC="img215.gif"  > '; 
$key = q/{displaymath}tan^-1left(-k+sqrtk^2+4over2right),{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=337 HEIGHT=48 ALIGN=BOTTOM ALT="displaymath2389" SRC="img92.gif"  > '; 
$key = q/{_inline}$2sigma_i^2(a_i^2+a_i^-2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=95 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2601" SRC="img127.gif"  > '; 
$key = q/{_inline}$sigmaalpha${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=20 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline2899" SRC="img205.gif"  > '; 
$key = q/{_inline}$mathaccent;SPMquot;7016relaxy=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2311" SRC="img170.gif"  > '; 
$key = q/{_inline}$R(theta)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=31 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2425" SRC="img62.gif"  > '; 
$key = q/{_inline}$sigma_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2403" SRC="img50.gif"  > '; 
$key = q/{_inline}$ox^2-oy^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=50 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2693" SRC="img162.gif"  > '; 
$key = q/{_inline}$RrightarrowoR${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=49 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2647" SRC="img151.gif"  > '; 
$key = q/{_inline}$Psi_1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2305" SRC="img4.gif"  > '; 
$key = q/{_inline}$theta_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2345" SRC="img19.gif"  > '; 
$key = q/{_inline}$vecu=vec0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=39 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline2915" SRC="img213.gif"  > '; 
$key = q/{_inline}$Dvecu(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=48 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2415" SRC="img59.gif"  > '; 
$key = q/{_inline}$c_i^rmOdd${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=31 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2751" SRC="img183.gif"  > '; 
$key = q/{_inline}$sigma=0.3${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline3095" SRC="img252.gif"  > '; 
$key = q/{_inline}$lrightarrow0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=38 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2337" SRC="img16.gif"  > '; 
$key = q/{_inline}$oy${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline2681" SRC="img158.gif"  > '; 
$key = q/{_inline}$a_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2471" SRC="img79.gif"  > '; 
$key = q/{_inline}$oT^2=ox^2overa^2-oy^2a^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=106 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline2685" SRC="img160.gif"  > '; 
$key = q/{_inline}$O(l^2logl)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=66 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2347" SRC="img22.gif"  > '; 
$key = q/{_inline}$calE(l_1,l_2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=52 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2625" SRC="img138.gif"  > '; 
$key = q/{_inline}$l_1=Ra${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=53 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2631" SRC="img141.gif"  > '; 
$key = q/{_inline}$lambda_M${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=21 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2441" SRC="img69.gif"  > '; 
$key = q/{figure}[t]centerepsfysize=2.5inepsfboxfigsconv-dipole.epscenterlabelfig.conv-dipole{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=307 HEIGHT=274 ALIGN=BOTTOM ALT="figure1067" SRC="img254.gif"  > '; 
$key = q/{_inline}$vecu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2385" SRC="img40.gif"  > '; 
$key = q/{_inline}$oy=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2709" SRC="img170.gif"  > '; 
$key = q/{_inline}$vx_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2535" SRC="img101.gif"  > '; 
$key = q/{_inline}$(y-y_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3131" SRC="img259.gif"  > '; 
$key = q/{_inline}$a_i^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2405" SRC="img51.gif"  > '; 
$key = q/{_inline}$ain[1,a_M]${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=73 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2939" SRC="img220.gif"  > '; 
$key = q/{_inline}$alphain(0,1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=64 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2891" SRC="img199.gif"  > '; 
$key = q/{_inline}$psi_1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2653" SRC="img153.gif"  > '; 
$key = q/{_inline}$sigma=alphal${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=45 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2923" SRC="img216.gif"  > '; 
$key = q/{_inline}$alpharightarrow1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=42 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2895" SRC="img202.gif"  > '; 
$key = q/{_inline}$Cl^4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2581" SRC="img122.gif"  > '; 
$key = q/{_inline}$oR${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2677" SRC="img156.gif"  > '; 
$key = q/{_inline}$doverdt(a^2+a^-2)=a^-2(a^2-a^-2)doverdt(a^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=248 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3139" SRC="img265.gif"  > '; 
$key = q/{_inline}$epsilon=0.2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=47 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2317" SRC="img9.gif"  > '; 
$key = q/{_inline}$D^3vecu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=31 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2559" SRC="img112.gif"  > '; 
$key = q/{_inline}$lambda_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2303" SRC="img3.gif"  > '; 
$key = q/{_inline}$psi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2731" SRC="img174.gif"  > '; 
$key = q/{_inline}$gamma_0l^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2965" SRC="img230.gif"  > '; 
$key = q/{_inline}$fracd_12,i+d_21,i2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=62 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline2505" SRC="img93.gif"  > '; 
$key = q/{_inline}$Dvu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2429" SRC="img39.gif"  > '; 
$key = q/{_inline}$tin[0,T]${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=59 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2897" SRC="img203.gif"  > '; 
$key = q/{_inline}$widehat{}omega(x,y,t)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=101 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline2377" SRC="img33.gif"  > '; 
$key = q/{_inline}$c_i^rmEven${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2749" SRC="img182.gif"  > '; 
$key = q/{_inline}$nuneq0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2453" SRC="img71.gif"  > '; 
$key = q/{_inline}$gamma=pi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=39 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline3063" SRC="img244.gif"  > '; 
$key = q/{_inline}$g_0-g_1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=47 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2905" SRC="img207.gif"  > '; 
$key = q/{_inline}$vecu(vecx)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2409" SRC="img55.gif"  > '; 
$key = q/{_inline}$O(l^2(a^2-1))${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=90 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2457" SRC="img75.gif"  > '; 
$key = q/{_inline}$l^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2319" SRC="img10.gif"  > '; 
$key = q/{_inline}$nu=10^-2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=61 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline3065" SRC="img245.gif"  > '; 
$key = q/{_inline}$Rin[0,oR]${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=66 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2721" SRC="img173.gif"  > '; 
$key = q/{_inline}$O(l^4)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2335" SRC="img15.gif"  > '; 
$key = q/{_inline}$partial_xv=partial_xxpsi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=80 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2809" SRC="img189.gif"  > '; 
$key = q/{_inline}$mathaccent;SPMquot;0362relaxomega(mathaccent;SPMquot;017Erelaxx)-omega(mathaccent;SPMquot;017Erelaxx)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=82 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2323" SRC="img12.gif"  > '; 
$key = q/{_inline}$ai^2-1=(a_i-1)(ai+1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=170 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2615" SRC="img132.gif"  > '; 
$key = q/{_inline}$gamma_i=O(l^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=71 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2585" SRC="img124.gif"  > '; 
$key = q/{table}tabular|l|l|hlineFunction;SPMamp;hlinehline_inline$c_0^rmEven$_inline;SPMamp;_inline$arrayr1overoR^2left[1-4epsilonoT^2overoR^2+epsilon^2left(-8+16oT^4overoR^4right)+epsilon^3left(52oT^2overoR^2-64oT^6overoR^6right)+right.left.epsilon^4left(48-288oT^4overoR^4+256oT^8overoR^8right)right]array$_inlinehline_inline$c_0^rmOdd$_inline;SPMamp;_inline$0$_inlinehline_inline$c_1^rmEven$_inline;SPMamp;_inline$arrayrepsilonoveroR^4left[4oT^2overoR^2+epsilonleft(16-48oT^4overoR^4right)+epsilon^2left(-244oT^2overoR^2+384oT^6overoR^6right)+right.left.epsilon^3left(-288+2400oT^4overoR^4-2560oT^8overoR^8right)right]array$_inlinehline_inline$c_1^rmOdd$_inline;SPMamp;_inline$epsilonoveroR^4left[-2+epsilon16oT^2overoR^2+epsilon^2left(26-96oT^4overoR^4right)+epsilon^3left(-288oT^2overoR^2+512oT^6overoR^6right)right]$_inlinehline_inline$c_2^rmEven$_inline;SPMamp;_inline$arrayrepsilon^2overoR^6left[-8+32oT^4overoR^4+epsilonleft(352oT^2overoR^2-640oT^6overoR^6right)+right.left.epsilon^2left(656-6464oT^4overoR^4+7680oT^8overoR^8right)right]array$_inlinehline_inline$c_2^rmOdd$_inline;SPMamp;_inline$arrayrepsilon^2overoR^6left[-16oT^2overoR^2+epsilonleft(-64+256oT^4overoR^4right)+epsilon^2left(1312oT^2overoR^2-2560oT^6overoR^6right)right]array$_inlinehline_inline$c_3^rmEven$_inline;SPMamp;_inline$arrayrepsilon^3overoR^8left[left(-160oT^2overoR^2+320oT^6overoR^6right)+epsilonleft(-640+7040oT^4overoR^4-8960oT^8overoR^8right)right]array$_inlinehline_inline$c_3^rmOdd$_inline;SPMamp;_inline$arrayrepsilon^3overoR^8left[left(40-160oT^4overoR^4right)+epsilonleft(-1920oT^2overoR^2+3840oT^6overoR^6right)right]array$_inlinehline_inline$c_4^rmEven$_inline;SPMamp;_inline$arrayrepsilon^4overoR^10left(224-2688oT^4overoR^4+3584oT^8overoR^8right)array$_inlinehline_inline$c_4^rmOdd$_inline;SPMamp;_inline$arrayrepsilon^4overoR^10left(896oT^2overoR^2-1792oT^6overoR^6right)array$_inlinehline_inline$c_5^rmEven$_inline;SPMamp;_inline$1$_inlinehline_inline$c_5^rmOdd$_inline;SPMamp;_inline$-2epsilon+2epsilon^3$_inlinehlinetabularlabeltab.vel.coefficients{table}/;
$cached_env_img{$key} = ' <IMG WIDTH=519 HEIGHT=432 ALIGN=BOTTOM ALT="table656" SRC="img186.gif"  > '; 
$key = q/{_inline}$a^2-1=O(l^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=100 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2465" SRC="img78.gif"  > '; 
$key = q/{_inline}$-9.3times10^-4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=83 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2331" SRC="img14.gif"  > '; 
$key = q/{_inline}$D^3vecu(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=55 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2537" SRC="img102.gif"  > '; 
$key = q/{_inline}$Asimr^2=O[l^2(1-alpha^2)]${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=158 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2973" SRC="img233.gif"  > '; 
$key = q/{_inline}$d_12,i=duoverdy(vx_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=95 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2419" SRC="img61.gif"  > '; 
$key = q/{figure}[t]centerparbox2.5inepsfxsize=2.5inepsfboxfigsdipole104b0020.epsparbox2.5inepsfxsize=2.5inepsfboxfigsdipole104b0020-zoom.epscenterlabelfig.dipole-positions{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=575 HEIGHT=306 ALIGN=BOTTOM ALT="figure1061" SRC="img253.gif"  > '; 
$key = q/{_inline}$xirightarroworho^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=47 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2641" SRC="img148.gif"  > '; 
$key = q/{_inline}$a=alphaa_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=54 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2931" SRC="img218.gif"  > '; 
$key = q/{figure}[t]centerparbox1.65inepsfxsize=1.65inepsfboxfigsdipole103d0000.epsparbox1.65inepsfxsize=1.65inepsfboxfigsdipole103d0010.epsparbox1.65inepsfxsize=1.65inepsfboxfigsdipole103d0020.epscenterlabelfig.dipole-evolve{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=577 HEIGHT=202 ALIGN=BOTTOM ALT="figure1047" SRC="img249.gif"  > '; 
$key = q/{_inline}$theta${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=7 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2427" SRC="img63.gif"  > '; 
$key = q/{_inline}$|1-a_M^2|siml^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=90 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2993" SRC="img238.gif"  > '; 
$key = q/{_inline}$l_1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2621" SRC="img135.gif"  > '; 
$key = q/{_inline}$psi_2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2649" SRC="img152.gif"  > '; 
$key = q/{_inline}$1-a_i^2=(1-a_i)(1+a_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=169 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2529" SRC="img97.gif"  > '; 
$key = q/{_inline}$partial_yv=-partial_xu=partial_xypsi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=138 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2811" SRC="img191.gif"  > '; 
$key = q/{_inline}$sigma_1=alphasigma_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=63 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2893" SRC="img200.gif"  > '; 
$key = q/{_inline}$vecxi_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=34 ALIGN=MIDDLE ALT="tex2html_wrap_inline2539" SRC="img103.gif"  > '; 
$key = q/{_inline}$gamma_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline2407" SRC="img53.gif"  > '; 
$key = q/{_inline}$sigma_i;SPMlt;l${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=40 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2437" SRC="img67.gif"  > '; 
$key = q/{_inline}$partial_xu=-partial_xypsi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=92 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2741" SRC="img179.gif"  > '; 
$key = q/{_inline}$partial_yu=-partial_yypsi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=92 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2807" SRC="img187.gif"  > '; 
$key = q/{_inline}$vx${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline3133" SRC="img260.gif"  > '; 
$key = q/{_inline}$piR^2(-partial_Rf)dR${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=102 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2629" SRC="img140.gif"  > '; 
$key = q/{_inline}$sigma^2in[alpha^2sigma^2,sigma^2]${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=102 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2605" SRC="img129.gif"  > '; 
$key = q/{_inline}$u^(1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=25 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline3125" SRC="img256.gif"  > '; 
$key = q/{figure}[t]centerparbox2.5inepsfxsize=2.5inepsfboxfigsabserr4.epsparbox2.5inepsfxsize=2.5inepsfboxfigserr-test81d.epscenterlabelfig.conv-gaussian{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=557 HEIGHT=249 ALIGN=BOTTOM ALT="figure1034" SRC="img248.gif"  > '; 
$key = q/{_inline}$mathaccent;SPMquot;7016relaxx=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2309" SRC="img169.gif"  > '; 
$key = q/{_inline}$vu(x,y,t)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=58 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2353" SRC="img25.gif"  > '; 
$key = q/{_inline}$Rwidehat{}omega${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=66 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline2379" SRC="img34.gif"  > '; 
$key = q/{_inline}$ox^2+oy^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=50 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2691" SRC="img161.gif"  > '; 
$key = q/{_inline}$epsilon${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=6 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline2659" SRC="img154.gif"  > '; 
$key = q/{_inline}$orho^2=ox^2+oy^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=87 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2637" SRC="img146.gif"  > '; 
$key = q/{table}tabular|l|l|hlineFunction;SPMamp;hlinehline_inline$d_0^rmEven$_inline;SPMamp;_inline$arrayr1overoR^2left[-1+8epsilonoT^2overoR^2+epsilon^2left(16-48oT^4overoR^4right)+epsilon^3left(-168oT^2overoR^2+256oT^6overoR^6right)+right.left.epsilon^4left(-160+1248oT^4overoR^4-1280oT^8overoR^8right)right]array$_inlinehline_inline$d_0^rmOdd$_inline;SPMamp;_inline$0$_inlinehline_inline$d_1^rmEven$_inline;SPMamp;_inline$arrayrepsilonoveroR^4left[-12oT^2overoR^2+epsilonleft(-48+192oT^4overoR^4right)+epsilon^2left(1020oT^2overoR^2-1920oT^6overoR^6right)+right.left.epsilon^3left(1248-12672oT^4overoR^4+15360oT^8overoR^8right)right]array$_inlinehline_inline$d_1^rmOdd$_inline;SPMamp;_inline$epsilonoveroR^4left[8-epsilon96oT^2overoR^2+epsilon^2left(-168+768oT^4overoR^4right)+epsilon^3left(2496oT^2overoR^2-5120oT^6overoR^6right)right]$_inlinehline_inline$d_2^rmEven$_inline;SPMamp;_inline$arrayrepsilon^2overoR^6left[8-160oT^4overoR^4+epsilonleft(-1408oT^2overoR^2+3840oT^6overoR^6right)+right.left.epsilon^2left(-2768+36160oT^4overoR^4-53760oT^8overoR^8right)right]array$_inlinehline_inline$d_2^rmOdd$_inline;SPMamp;_inline$arrayrepsilon^2overoR^6left[128oT^2overoR^2+epsilonleft(512-2560oT^4overoR^4right)+epsilon^2left(-13568oT^2overoR^2+30720oT^6overoR^6right)right]array$_inlinehline_inline$d_3^rmEven$_inline;SPMamp;_inline$arrayrepsilon^3overoR^8left[left(480oT^2overoR^2+-2240oT^6overoR^6right)+epsilonleft(1920-38400oT^4overoR^4+71680oT^8overoR^8right)right]array$_inlinehline_inline$d_3^rmOdd$_inline;SPMamp;_inline$arrayrepsilon^3overoR^8left[left(-320+1920oT^4overoR^4right)+epsilonleft(21760oT^2overoR^2-53760oT^6overoR^6right)right]array$_inlinehline_inline$d_4^rmEven$_inline;SPMamp;_inline$arrayrepsilon^4overoR^10left(-224+13440oT^4overoR^4-32256oT^8overoR^8right)array$_inlinehline_inline$d_4^rmOdd$_inline;SPMamp;_inline$arrayrepsilon^4overoR^10left(-10752oT^2overoR^2+28672oT^6overoR^6right)array$_inlinehline_inline$d_5^rmEven$_inline;SPMamp;_inline$0$_inlinehline_inline$d_5^rmOdd$_inline;SPMamp;_inline$0$_inlinehline_inline$e_2$_inline;SPMamp;_inline$arrayrepsilon^2overoR^6left[40-160oT^4overoR^4+epsilonleft(-1920oT^2overoR^2+3840oT^6overoR^6right)+right.left.epsilon^2left(-3600+41280oT^4overoR^4-53760oT^8overoR^8right)right]array$_inlinehline_inline$e_3$_inline;SPMamp;_inline$arrayrepsilon^3overoR^8left[left(1120oT^2overoR^2-2240oT^6overoR^6right)+epsilonleft(4480-53760oT^4overoR^4+71680oT^8overoR^8right)right]array$_inlinehline_inline$e_4$_inline;SPMamp;_inline$arrayrepsilon^4overoR^10left(-2016+24192oT^4overoR^4-32256oT^8overoR^8right)array$_inlinehlinetabularlabeltab.veldev.coefficients{table}/;
$cached_env_img{$key} = ' <IMG WIDTH=545 HEIGHT=550 ALIGN=BOTTOM ALT="table773" SRC="img193.gif"  > '; 
$key = q/{_inline}$theta_i(t)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=30 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2393" SRC="img44.gif"  > '; 
$key = q/{_inline}$v=partial_xpsi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=56 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2739" SRC="img178.gif"  > '; 
$key = q/{_inline}$alpha${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline2329" SRC="img13.gif"  > '; 
$key = q/{_inline}$s_ic_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2489" SRC="img87.gif"  > '; 
$key = q/{_inline}$c_is_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=24 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2491" SRC="img89.gif"  > '; 
$key = q/{_inline}$sigma_ileql${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=40 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2563" SRC="img117.gif"  > '; 
$key = q/{_inline}$theta_i^+${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=17 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2493" SRC="img85.gif"  > '; 
$key = q/{_inline}$sigma_i=alphal${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=50 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline3053" SRC="img241.gif"  > '; 
$key = q/{_inline}$vec0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=9 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline2543" SRC="img105.gif"  > '; 
$key = q/{_inline}$a=a_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2935" SRC="img219.gif"  > '; 
$key = q/{_inline}$widehatomega${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2387" SRC="img41.gif"  > '; 
$key = q/{_inline}$a_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2941" SRC="img221.gif"  > '; 
$key = q/{_inline}$intint(x^2+y^2)f(x,y)dxdy${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=166 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2885" SRC="img195.gif"  > '; 
$key = q/{_inline}$sigma${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=9 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline2669" SRC="img155.gif"  > '; 
$key = q/{_inline}$alpha^2l^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2321" SRC="img11.gif"  > '; 
$key = q/{_inline}$1-alpha^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=43 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2997" SRC="img239.gif"  > '; 
$key = q/{_inline}$ox=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2707" SRC="img169.gif"  > '; 
$key = q/{figure}[t]centerepsfysize=2.5inepsfboxfigssize104b.epscenterlabelfig.merge{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=309 HEIGHT=274 ALIGN=BOTTOM ALT="figure1019" SRC="img242.gif"  > '; 
$key = q/{_inline}$gamma_0l^2=Oleft[l^2(p-1)right]${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=128 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2969" SRC="img232.gif"  > '; 
$key = q/{_inline}$(x-x_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=53 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3129" SRC="img258.gif"  > '; 
$key = q/{_inline}$Dvecu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2383" SRC="img39.gif"  > '; 
$key = q/{_inline}$d_11,i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2299" SRC="img1.gif"  > '; 
$key = q/{_inline}$vx_i(t)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=31 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2391" SRC="img43.gif"  > '; 
$key = q/{_inline}$l_2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2623" SRC="img136.gif"  > '; 
$key = q/{_inline}$sigma_i(t)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=31 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2397" SRC="img46.gif"  > '; 
$key = q/{_inline}$O(N^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2981" SRC="img235.gif"  > '; 
$key = q/{_inline}$Cl^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2575" SRC="img121.gif"  > '; 
$key = q/{_inline}$x_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2953" SRC="img223.gif"  > '; 
$key = q/{_inline}$sigma_ia_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=27 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline2341" SRC="img18.gif"  > '; 
$key = q/{_inline}$ox=1over2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=39 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2711" SRC="img171.gif"  > '; 
$key = q/{_inline}$oT${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2683" SRC="img159.gif"  > '; 
$key = q/{_inline}$theta=0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline2617" SRC="img133.gif"  > '; 
$key = q/{_inline}$partial_Rf${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=28 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2735" SRC="img176.gif"  > '; 
$key = q/{_inline}$x_i=2r(i-n2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=113 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2947" SRC="img222.gif"  > '; 
$key = q/{_inline}$s_i=0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=41 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2553" SRC="img108.gif"  > '; 
$key = q/{_inline}$epsilon=0.4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=48 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2307" SRC="img5.gif"  > '; 
$key = q/{_inline}$vu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2363" SRC="img40.gif"  > '; 
$key = q/{_inline}$Rrightarrow0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=45 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2643" SRC="img149.gif"  > '; 
$key = q/{_inline}$omega=(nablatimesvu)cdotwidehatz${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=107 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2355" SRC="img26.gif"  > '; 
$key = q/{_inline}$gamma=4pi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=47 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline3093" SRC="img251.gif"  > '; 
$key = q/{_inline}$l_2=Ra${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=61 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2633" SRC="img142.gif"  > '; 
$key = q/{_inline}$a_i(t)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=31 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2395" SRC="img45.gif"  > '; 
$key = q/{_inline}$sigma=1over4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=40 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline3067" SRC="img246.gif"  > '; 
$key = q/{_inline}$x^(2)=y${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=55 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline2557" SRC="img111.gif"  > '; 
$key = q/{_inline}$1-a_i^2=O(l^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=99 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2527" SRC="img96.gif"  > '; 
$key = q/{_inline}$u=-partial_ypsi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=69 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2737" SRC="img177.gif"  > '; 
$key = q/{displaymath}vu=ubrackv=-partialpsioverpartialybrackpartialpsioverpartialx{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=311 HEIGHT=48 ALIGN=BOTTOM ALT="displaymath2607" SRC="img139.gif"  > '; 
$key = q/{table}[t]centertabular|l|l|l|hline_inline$l^2$_inline;SPMamp;_inline$alpha$_inline;SPMamp;_inline$alpha^2l^2$_inlinehlinehline_inline$4.0times10^-2$_inline;SPMamp;_inline$0.8$_inline;SPMamp;_inline$2.56100times10^-2$_inlinehline_inline$3.5times10^-2$_inline;SPMamp;_inline$0.81440$_inline;SPMamp;_inline$2.32138times10^-2$_inlinehline_inline$3.0times10^-2$_inline;SPMamp;_inline$0.82960$_inline;SPMamp;_inline$2.06470times10^-2$_inlinehline_inline$2.5times10^-2$_inline;SPMamp;_inline$0.84581$_inline;SPMamp;_inline$1.78849times10^-2$_inlinehline_inline$2.0times10^-2$_inline;SPMamp;_inline$0.86339$_inline;SPMamp;_inline$1.49089times10^-2$_inlinehline_inline$1.5times10^-2$_inline;SPMamp;_inline$0.88292$_inline;SPMamp;_inline$1.16932times10^-2$_inlinehline_inline$1.0times10^-2$_inline;SPMamp;_inline$0.90554$_inline;SPMamp;_inline$8.20000times10^-3$_inlinehlinetabularcenterlabeltab.conv-gaussian{table}/;
$cached_env_img{$key} = ' <IMG WIDTH=288 HEIGHT=162 ALIGN=BOTTOM ALT="table993" SRC="img240.gif"  > '; 
$key = q/{_inline}$Asiml^2p${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap_inline2967" SRC="img231.gif"  > '; 
$key = q/{_inline}$a_i^2leqa_M^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=58 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2455" SRC="img72.gif"  > '; 
$key = q/{_inline}$c_i=cos(theta_i)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=79 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2399" SRC="img48.gif"  > '; 
$key = q/{_inline}$Dvecu(vecx)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=43 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2411" SRC="img56.gif"  > '; 
$key = q/{_inline}$O(NlogN)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=78 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2983" SRC="img236.gif"  > '; 
$key = q/{_inline}$lambda${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2909" SRC="img212.gif"  > '; 
$key = q/{_inline}$O(l^8)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2531" SRC="img98.gif"  > '; 
$key = q/{_inline}$a_irightarrow1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=46 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2473" SRC="img80.gif"  > '; 
$key = q/{_inline}$s^2-c^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=46 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline3141" SRC="img267.gif"  > '; 
$key = q/{_inline}$mathaccent;SPMquot;7016relaxx=1over2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=39 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2313" SRC="img171.gif"  > '; 
$key = q/{_inline}$oR^2=ox^2overa^2+oy^2a^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=107 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline2639" SRC="img147.gif"  > '; 
$key = q/{_inline}$ox${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=9 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline2679" SRC="img157.gif"  > '; 
$key = q/{_inline}$1-a_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=39 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2525" SRC="img95.gif"  > '; 
$key = q/{keywords}vortexmethods,vorticitydynamics,computationalfluiddynamics,convergencetheory{keywords}/;
$cached_env_img{$key} = ' <IMG WIDTH=589 HEIGHT=27 ALIGN=BOTTOM ALT="keywords72" SRC="img20.gif"  > '; 
$key = q/{_inline}$theta^+_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=17 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2479" SRC="img85.gif"  > '; 
$key = q/{displaymath}cs(a^-2-a^2)[(c^2a^-2+s^2a^2)+(s^2a^-2+c^2a^2)]=cs(a^-4-a^4){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=463 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath3119" SRC="img262.gif"  > '; 
$key = q/{_inline}$omega${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=7 ALIGN=BOTTOM ALT="tex2html_wrap_inline2375" SRC="img31.gif"  > '; 
$key = q/{_inline}$theta^-_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=17 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2481" SRC="img86.gif"  > '; 
$key = q/{_inline}$oS^2=ox^2-oy^2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=88 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline2699" SRC="img165.gif"  > '; 

1;

